daemon off;
pid /run/nginx.pid;
worker_processes auto;
user www-data;
events {
    worker_connections 768;
}
error_log /proc/self/fd/2 warn;

http {
    access_log /proc/self/fd/1;

    # compression
    gzip on;
    server_tokens off;

    include mime.types;

    server {
        listen 80;
        server_name _;
        root /app;
        charset utf-8;

        # auth
        auth_basic "auth";
        auth_basic_user_file /etc/nginx/.htpasswd;

        # make h5ai the directory index
        index /_h5ai/public/index.php;

        # serve files normally; directories fall through to h5ai
        location / {
            try_files $uri $uri/ /_h5ai/public/index.php?$args;
        }

        # php
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass unix:/run/php/php-fpm.sock;
        }

        # block h5ai internals
        location ^~ /_h5ai/private/ { deny all; }
    }
}